### ISSUE TITLE
Missing LICENSE file?

### ISSUE THREAD

**Issue by zoobab** [jeanthom/DirtyJTAG#101]
Hi,

During the Gerrit code review of openocd patches, someone raised the issue of a missing LICENSE file.

We should add one for the clarity, which one should we use?

Best

**Comment by jeanthom** [comment]
Hi Benjamin,

The source code of DirtyJTAG has always been available under the MIT license, as stated in every source file header - in that sense there is no licensing ambiguity. However I do agree that adding a LICENSE file would improve clarity.
