### ISSUE TITLE
Wrong pinout on the photo of bluepill?

### ISSUE THREAD

**Issue by KnorkFox** [jeanthom/DirtyJTAG#109]
Hi, i have seen, that you used ports A1 to A7 for the jtag signals. On the table nearby is written, Pa0 to Pa5.

I have used the release 2.0 image. [dirtyjtag.bluepill.noloader.bin](https://github.com/dirtyjtag/DirtyJTAG/releases/download/2.0/dirtyjtag.bluepill.noloader.bin)

What is wrong, the table, or the photo, or am i just confused?

**Comment by jeanthom** [comment]
Hi,

Thanks for pointing this confusing documentation page. The source of truth is the `jtag.c` file: https://github.com/dirtyjtag/DirtyJTAG/blob/master/src/jtag.c#L79-L99

Therefore the image is correct (it actually uses PA2-PA7) but the table isn't. I'll fix this in a minute.

Jean

**Comment by KnorkFox** [comment]
Thanks a lot! Now it is clear to me.

I want to flash memory chips with flashrom. Since dirtyjtag is now supported by flashrom V 1.3

Bluepill  SPI

Pin 2 = # WP
Pin 3 = # CS
Pin 4 = # Hold
Pin 5 = CLK
Pin 6 = MISO
Pin 7 = MOSI
gnd  = ground
