### ISSUE TITLE
Bluepill flashing using UART bootloader

### ISSUE THREAD

**Issue by jeanthom** [jeanthom/DirtyJTAG#11]
Bluepill (and blackpill) boards are flashed with a serial bootloader. We could use this to flash DirtyJTAG without an SWD programmer.

Builds that are compatible with bootloaders have to be compiled with a special linker script.

**Comment by zoobab** [comment]
Mostly done now.

**Comment by zoobab** [comment]
Can you close that issue? I don't have the perms to do it...

**Comment by jeanthom** [comment]
Does it erases the bootloader ?
