### ISSUE TITLE
typo in building-dity jtag.md

### ISSUE THREAD

**Issue by KnorkFox** [jeanthom/DirtyJTAG#111]
noloader: No bootloader
loader2k: Bootloader is occupying 0x0-0x2000, DirtyJTAG starts at 0x2000 offset
loader2k: Bootloader is occupying 0x0-0x4000, DirtyJTAG starts at 0x4000 offset

The third line must be **loader4k:**

It would be nice, when you can explain, why a loader is needed, and why there are two different loader available. Thanks!

**Comment by jeanthom** [comment]
Hi, thanks for the suggestion. I tried improving the doc in #112, let me know if this is clearer.
