### ISSUE TITLE
Pinout stickers for ST-Link v2 clones

### ISSUE THREAD

**Issue by jeanthom** [jeanthom/DirtyJTAG#12]
Making printing-friendly sticker for gluing on top of the engraved pinout.

**Comment by jeanthom** [comment]
I've made a black and white-friendly sticker :

![DirtyJTAG pinout sticker](https://github.com/jeanthom/DirtyJTAG/blob/master/docs/img/stlinkv2-sticker.svg)

**Comment by zoobab** [comment]
Any idea how to convert this to a PD? SVG is nice, but I don't know how it handles the right scale when you print it.

**Comment by psyborg55** [comment]
hi

do you know pinout of baite stlink v2 when flashed? since it support jtag is there an alternative to firmware flashing? want to use it with urjtag
