### ISSUE TITLE
Make a docker automated build on docker hub

### ISSUE THREAD

**Issue by zoobab** [jeanthom/DirtyJTAG#22]
Make a docker automated build on docker hub, that would require probably creating an organization that has access to this repo.

Add a build logo (success/failure) on the frontpage if possible.

**Comment by jeanthom** [comment]
I have just added Travis CI for build status. Travis can also create GitHub Releases ([documentation](https://docs.travis-ci.com/user/deployment/releases/)) but it requires publishing an Oauth key, which is what I do not want to do...

**Comment by jeanthom** [comment]
I close this as "wontfix" as automated build isn't a priority, regarding the current activity on this repository.
