### ISSUE TITLE
Add white ST-Link/V2 support

### ISSUE THREAD

**Issue by jeanthom** [jeanthom/DirtyJTAG#46]
According to http://www.diygoodies.org.ua/?p=417 the pinout should be the following:

```
TCK PA5
TDO PA6
TDI PA7
TMS PB14
NRST PB0
JRST PB1
```

**Comment by zoobab** [comment]
By white you mean this one?

https://img3.bgxcdn.com/thumb/large/oaupload/banggood/images/47/78/161465dd-84a2-4054-17d2-e43280df1f8c.jpg

**Comment by jeanthom** [comment]
Yup the one you gave me. I still have to verify the pinout listed above.

**Comment by jeanthom** [comment]
* [x] Make PR for code changes
 * [x] Finish the JTAG test wiring board
 * [x] Add documentation
