### ISSUE TITLE
driver not found

### ISSUE THREAD

**Issue by dunk8888** [jeanthom/DirtyJTAG#64]
Hi what driver do i use for the firmware

**Comment by jeanthom** [comment]
Hi, the DirtyJTAG driver in integrated into UrJTAG so there's no need for an external driver.

You'll need a recent version of UrJTAG though (>= 2018 release). If your Linux distribution does not provide a recent version then I advise you to follow this step-by-step tutorial: https://github.com/jeanthom/DirtyJTAG/blob/master/docs/urjtag-dirtyjtag.md

**Comment by dunk8888** [comment]
Ok thanks☺
