### ISSUE TITLE
stm32flash write protected

### ISSUE THREAD

**Issue by aalku** [jeanthom/DirtyJTAG#70]
Hello! Great software. Thank you for it.
I was trying to use this:
https://github.com/jeanthom/DirtyJTAG/blob/master/docs/install-bluepill.md

And I needed to unprotect my stm32 with this commands first. I think it would be helpfull if you put them in the doc because people are using the vendor propietary sofware for windows to unlock because then don't know stm32flash can do it. I almost use that software too.

If you get a NACK when trying to erase you need to remove write protection and if you get a NACK trying to make write unprotection then you need to remove read protection first. So I put the two commands.

```
stm32flash -k /dev/ttyUSB0
stm32flash -u /dev/ttyUSB0
```

Thank you again.

Reference: http://stm32duinoforum.com/forum/viewtopic_f_20_t_747.html

**Comment by jeanthom** [comment]
Didn't notice your issue for a while, sorry... Thanks for your help, I've included your advice in #85 which will be merged soon!
