### ISSUE TITLE
superfluous -g 0x8000000 for stm32flash

### ISSUE THREAD

**Issue by nerdralph** [jeanthom/DirtyJTAG#71]
Since the boot0 jumper will be removed and the power cycled after flashing, there is no point in adding the "-g 0x8000000" to tell the bootloader to jump to the start of flash after writing.

**Comment by jeanthom** [comment]
Hi,

This flag might be useful for debugging purposes? Actually I've never used stm32flash. @zoobab what's your opinion on this?

**Comment by zoobab** [comment]
He is probably right, this can be removed.

Before discovering stm32flash, I was using another python tool which I had real problems with:

http://www.zoobab.com/bluepill-arduinoide

**Comment by jeanthom** [comment]
Ok I'll remove it from the docs then. Thanks @nerdralph for raising this issue, and thanks @zoobab for your input.
