### ISSUE TITLE
Add a link to openFPGALoader?

### ISSUE THREAD

**Issue by zoobab** [jeanthom/DirtyJTAG#73]
OpenFPGALoader is supporting DirtyJTAG, it would be good to add at least a link to the project, if not a nice picture and a screenshot:

https://github.com/trabucayre/openFPGALoader

**Comment by jeanthom** [comment]
Will do. A cheap ECP5 board + DirtyJTAG tutorial would be ideal.

**Comment by zoobab** [comment]
There is a good blogpost here:

https://blog.pcbxprt.com/index.php/2020/07/19/running-risc-v-core-on-small-fpga-board/

**Comment by jeanthom** [comment]
What do you think of #74?
