### ISSUE TITLE
UrJTAG: error: libusb error: libusb_init() failed: 6

### ISSUE THREAD

**Issue by dontdeadopeninside** [jeanthom/DirtyJTAG#98]
jtag> cable dirtyjtag
error: Couldn't connect to suitable USB device.
error: libusb error: libusb_init() failed: 6
jtag> 

Shows up properly in lsusb and dmesg

**Comment by jeanthom** [comment]
Hi,

It probably is a permission error. The short and hacky solution would be to run openFPGALoader/UrJTAG/whatever as a root user. The long and cleaner solution is to setup udev rules.

**Comment by dontdeadopeninside** [comment]
Unfortunately running as root and sudo both result in the same result, same with openFPGALoader

Shoot... i pressed close with comment on accident.... i don't use github a lot

**Comment by jeanthom** [comment]
Don't worry I can reopen issues.

Can you give me more information that could help me reproduce the issue?

 - Which hardware platform are you using?
 - What firmware version are you using? Did you compile it yourself?
 - What operating system are you using?

**Comment by jeanthom** [comment]
Closing issue due to lack to reply from original poster. Feel free to comment if the issue persists, I'll re-open the issue.
